CREATE TABLE CUSTOMER
ID BIGINT  NOT NULL PRIMARY KEY,
FIRST_NAME VARCHAR(255),
LAST_NAME VARCHAR(255),
PHONE VARCHAR(255),
CURP VARCHAR(255),
RFC VARCHAR(255),
ADDRESS VARCHAR(255);


CREATE TABLE ITEMS
id BIGINT NOT NULL PRIMARY KEY,
NAME VARCHAR(255),
PRICE DOUBLE;


CREATE TABLE IF NOT EXISTS ITEMS_BOUGHT
ORDER BIGINT NOT NULL PRIMARY KEY,
BOUGHT_DATE DATE, 
PRICE DOUBLE,
COMMENTS VARCHAR(255);
CUSTOMER_ID FOREIGN KEY REFERENCES CUSTOMER(ID)
ITEMS_ID BIGINT FOREIGN KEY REFERENCES ITEMS(ID);